# frontend_streamlit/.streamlit/secrets.toml

[firebase]
apiKey = "YOUR_FIREBASE_API_KEY"
authDomain = "YOUR_FIREBASE_PROJECT.firebaseapp.com"
projectId = "YOUR_FIREBASE_PROJECT_ID"
storageBucket = "YOUR_FIREBASE_PROJECT.appspot.com"
messagingSenderId = "YOUR_SENDER_ID"
appId = "YOUR_APP_ID"

[general]
DATABASE_URL = "sqlite:///../backend_fastapi/employee.db"
SECRET_KEY = "supersecretkey123"
